import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Poppins as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/theme-provider";
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight:"500"
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Repository Informatika",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
        
      >
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
